name: 'ninja-helm-upgrade'
description: 'ninja helm upgrade'
inputs:
  chart_name:
    required: true
    description: helm chart name
  values_set:
    required: false
    description: values to be passed to --set instruction to helm upgrade command
    default: ""
  helm_delete:
    required: true
    description: flag whether to delete helm chart before install/upgrade
  kube_config:
    required: true
    description: kube config file contents
  kube_namespace:
    required: true
    description: kube namespace to deploy to
  dockerhub_secret_name:
    required: false
    description: name of the k8s secret to create private docker registry config
    default: ''
  dockerhub_user:
    required: false
    description: username for dockerhub account
    default: ''
  dockerhub_password:
    required: false
    description: password for dockerhub account
    default: ''
  dockerhub_email:
    required: false
    description: email for dockerhub account
    default: ''
  chart_repo_name:
    required: false
    description: optional chart repository namespace
    default: ''
  chart_repo_url:
    required: false
    description: optional chart repository url (needs to be set together with chart_repo_name)
    default: ''
  deployment_name:
    required: false
    description: optional deployment name (if not set chart_name will be used a deployment name)
    default: ''
  custom_bash:
    required: false
    description: custom bash script to run before upgrade
    default: ''

runs:
  using: "composite"
  steps:
    - name: Helm deploy
      run: |
        # copy kube config from secrets
        mkdir -p ~/.kube/
        echo ${{ inputs.kube_config }} >> ~/.kube/config.encoded
        base64 ~/.kube/config.encoded > ~/.kube/config --decode

        # setting current namespace
        kubectl config set-context --current --namespace=${{ inputs.kube_namespace }}

        # connect private dockerhub registry
        if [ -n "${{ inputs.dockerhub_secret_name }}" ]; then
          kubectl delete secret ${{ inputs.dockerhub_secret_name }} --ignore-not-found
          kubectl create secret docker-registry ${{ inputs.dockerhub_secret_name }} --docker-server="https://index.docker.io/v1/" --docker-username=${{ inputs.dockerhub_user }} --docker-password=${{ inputs.dockerhub_password }} --docker-email=${{ inputs.dockerhub_email }}
        fi

        # adding helm chart repository if set
        if [ -n "${{ inputs.chart_repo_name }}" ]; then
            helm repo add "${{ inputs.chart_repo_name }}" "${{ inputs.chart_repo_url }}"
        fi

        DEPLOYMENT_NAME=${{ inputs.chart_name }}
        if [ -n "${{ inputs.deployment_name }}" ]; then
            DEPLOYMENT_NAME=${{ inputs.deployment_name }}
        fi

        # running custom bash script if set
        [ -n "${{ inputs.custom_bash }}" ] && eval "${{ inputs.custom_bash }}"

        # delete helm chart
        if [ -n "${{ inputs.helm_delete }}" ]; then
            helm delete $DEPLOYMENT_NAME --debug
        fi

        CHART_PATH=./deployment/${{ inputs.chart_name }}
        if [ -d "$CHART_PATH" ]; then
          echo "Installing helm from local chart path:" $CHART_PATH
        else
          CHART_PATH=${{ inputs.chart_name }}
          echo "Installing helm from chart repository:" $CHART_PATH
        fi

        REF=${{ github.ref }}
        # Strip git ref prefix from version
        VERSION=$(echo "$REF" | sed -e 's,.*/\(.*\),\1,')
        # # Strip "v" prefix from tag name
        # [[ "$REF" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

        # checking for values override
        VALUES_OVERRIDE_FILE=./deployment/$DEPLOYMENT_NAME/values.$VERSION.yaml

        if [ -f "$VALUES_OVERRIDE_FILE" ]; then
          echo "Using override file with helm values:" $VALUES_OVERRIDE_FILE
          # install/upgrade helm chart
          helm upgrade $DEPLOYMENT_NAME $CHART_PATH --set "${{ inputs.values_set }}" -f $VALUES_OVERRIDE_FILE --install --wait --debug
        else
          echo "Values override file does not exist:" $VALUES_OVERRIDE_FILE
          # install/upgrade helm chart
          helm upgrade $DEPLOYMENT_NAME $CHART_PATH --set "${{ inputs.values_set }}"  --install --wait --timeout 5m0s --debug
        fi

        export POD_NAME=$(kubectl get pods -l "app.kubernetes.io/name=$DEPLOYMENT_NAME,app.kubernetes.io/instance=$DEPLOYMENT_NAME" -o jsonpath="{.items[0].metadata.name}")
        echo $(kubectl logs $POD_NAME)
      shell: bash
